//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OsaGo.DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entitie : DbContext
    {
        private static Entitie _context;
        public Entitie()
            : base("name=Entitie")
        {
        }

        public static Entitie GetContext()
        {
            if (_context == null)
                _context = new Entitie();
            return _context;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cars> Cars { get; set; }
        public virtual DbSet<Categories> Categories { get; set; }
        public virtual DbSet<Drivers> Drivers { get; set; }
        public virtual DbSet<InsuranceCopmanyes> InsuranceCopmanyes { get; set; }
        public virtual DbSet<Licenses> Licenses { get; set; }
        public virtual DbSet<Marks> Marks { get; set; }
        public virtual DbSet<Models> Models { get; set; }
        public virtual DbSet<Passports> Passports { get; set; }
        public virtual DbSet<Policies> Policies { get; set; }
        public virtual DbSet<Regions> Regions { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
