//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OsaGo.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Policies
    {
        public string Number { get; set; }
        public string InsuranceCompany { get; set; }
        public System.DateTime RegistrationDate { get; set; }
        public System.DateTime ValidityPeriod { get; set; }
        public string LicenseSeries { get; set; }
        public string LicenseNumber { get; set; }
        public int CarId { get; set; }
        public int DriverId { get; set; }
        public decimal Price { get; set; }
    
        public virtual Cars Cars { get; set; }
        public virtual Drivers Drivers { get; set; }
        public virtual InsuranceCopmanyes InsuranceCopmanyes { get; set; }
    }
}
